#!/usr/bin/env python
from __future__ import print_function
import dbus
import time

bus = dbus.SessionBus()

print('Inhibiting...')

if 'org.gnome.ScreenSaver' in bus.list_names():
    # Ubuntu 13.10
    screensaver = bus.get_object('org.gnome.ScreenSaver', '/')

    while True:
        screensaver.SimulateUserActivity()
        time.sleep(10)

elif 'org.freedesktop.PowerManagement' in bus.list_names():
    # XFCE
    proxy = bus.get_object('org.freedesktop.PowerManagement',
                           '/org/freedesktop/PowerManagement/Inhibit')
    while True:
        cookie = proxy.Inhibit('inhibit-screensaver', 'inhibit-screensaver')
        time.sleep(10)
    proxy.Uninhibit(cookie)


# worked on Ubuntu 13.04 AFAICR:
#proxy = bus.get_object('org.gnome.SessionManager','/org/gnome/SessionManager')
#proxy.Inhibit('something',dbus.UInt32(0),'inhibiting',dbus.UInt32(8))

# newer?
# http://people.freedesktop.org/~hadess/idle-inhibition-spec/re01.html
#proxy = bus.get_object('org.freedesktop.ScreenSaver', '/ScreenSaver')
#cookie = proxy.Inhibit('inhibit-screensaver', 'inhibit-screensaver')
#proxy.Uninhibit(cookie)
